<?xml version="1.0" ?>
<robot name="kr2_robot_a810" model="a810" model-revision="051020-0" mechanical-revision="5" features="TIO" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="kr810_description">

  <!-- materials -->

  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>

  <material name="dark_gray">
    <color rgba="0.3 0.3 0.3 1.0"/>
  </material>

  <material name="light_gray">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>
  
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  
  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
  </material>

  <!-- globals -->
  <xacro:property name="joints_damping" value="0.1" />

  <!-- links -->

  <!-- all dimensions should be input as measured in the drawing in mm and
       converted to real dimensions by multiplying with the scale property -->
  <xacro:property name="scale" value="0.001" />

  <!-- <xacro:property name="pi" value="3.14159265359" /> -->
  <xacro:property name="pi_per_deg" value="${pi / 180.0}" />

  <xacro:property name="mass_multiplier" value="1.0" />

  <xacro:macro name="cylinder_inertia" params="mass radius length">
      <!--      <inertia ixx="${mass/12*(3*radius*radius+3*length*length)}"
               ixy="0.0"
               ixz="0.0"
               iyy="${mass/12*(3*radius*radius+3*length*length)}"
               iyz="0.0"
               izz="${mass*radius*radius/2}"/>
       -->
      <inertia ixx="0.003"
               ixy="0.0"
               ixz="0.0"
               iyy="0.003"
               iyz="0.0"
               izz="0.003"/>

  </xacro:macro>

  <xacro:macro name="visual_and_collision" params="xyz material rpy *geometry">
      <visual>
        <origin rpy="${rpy}" xyz="${xyz}" />
        <geometry>
          <xacro:insert_block name="geometry" />
        </geometry>
        <material name="${material}" />
      </visual>
      <collision>
        <origin rpy="${rpy}" xyz="${xyz}" />
        <geometry>
          <xacro:insert_block name="geometry" />
        </geometry>
      </collision>
  </xacro:macro>

  <!-- <link name="world"/> -->


  <link name="base">

    <xacro:property name="base_outer_radius" value="${ 80 * scale}" />
    <xacro:property name="base_inner_radius" value="${ 60 * scale}" />
    <xacro:property name="base_outer_height" value="${ 20 * scale}" />
    <xacro:property name="base_inner_height" value="${ 15 * scale}" />

    <xacro:property name="base_mass"         value="0.6" />
    <!--
    <xacro:visual_and_collision rpy="0 0 0"
                                xyz="0 0 ${base_outer_height / 2}"
                                material="dark_gray">
      <cylinder length="${base_outer_height}" radius="${base_outer_radius}"/>
    </xacro:visual_and_collision>

    <xacro:visual_and_collision rpy="0 0 0"
                                xyz="0 0 ${base_outer_height + base_inner_height/2}"
                                material="dark_gray">
      <cylinder length="${base_inner_height}" radius="${base_inner_radius}"/>
    </xacro:visual_and_collision>
    -->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="${base_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${base_mass}"
                              radius="${base_outer_radius}"
                              length="${base_inner_height+base_outer_height}" />
    </inertial>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="$(find kr_robot_description)/kr810/meshes/a810/a810_Base.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.2 0.2 0.2 1" />
        </material>
    </visual>


  </link>

  <link name="link1">

    <xacro:property name="link1_radius" value="${ 60 * scale}" />
    <xacro:property name="link1_length" value="${ 308.7 * scale - 35 * scale}" />
    <xacro:property name="link1_hinge_length"  value="${  130   * scale}"   />
    <xacro:property name="link1_hinge_radius"  value="${  57.5 * scale}" />

    <xacro:property name="link1_mass"   value="4.58" />
    <!--
    <xacro:visual_and_collision rpy="0 0 0"
                                xyz="0 0 ${link1_length/2 - 25 * scale}"
                                material="gray">
      <cylinder length="${link1_length - 50 * scale}" radius="${link1_radius}"/>
    </xacro:visual_and_collision>

    <xacro:visual_and_collision rpy="${pi/2} 0 0"
                                xyz="${50 * scale} ${20 * scale} ${link1_length}"
                                material="gray">
      <cylinder length="${link1_radius * 1.7}" radius="${link1_radius}"/>
    </xacro:visual_and_collision>
    
    <xacro:visual_and_collision rpy="0 ${pi/4} 0"
                                xyz="${20 * scale} ${+8 * scale} ${200 * scale}"
                                material="light_gray">
      <cylinder length="${90 * scale}" radius="${50 * scale}"/>
    </xacro:visual_and_collision>
    -->

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${link1_length/2}"/>
      <mass value="${link1_mass*mass_multiplier}"/>
            <xacro:cylinder_inertia mass="${link1_mass}"
                                    radius="${link1_radius}"
                                    length="${link1_length}" />
    </inertial>

    <visual>
        <origin xyz="0 0 0.169" rpy="0 0 0" />
        <geometry>
          <mesh filename="$(find kr_robot_description)/kr810/meshes/a810/a810_Link2.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.2 0.2 0.2 1" />
        </material>
    </visual>


  </link>

  <link name="linkJ2">

    <xacro:property name="cylinderJ2_radius"   value="${15 * scale}"   />
    <xacro:property name="cylinderJ2_height"   value="${120 * scale}"   />
    <xacro:property name="linkJ2_mass"         value="6.1"   />

    <xacro:visual_and_collision rpy="${pi/2} 0 0" 
                                xyz="0 ${-10 * scale} 0"
                                material="orange">
      <cylinder length="${cylinderJ2_height * 1.25}" radius="${cylinderJ2_radius}"/>
    </xacro:visual_and_collision>
    
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="${linkJ2_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${linkJ2_mass}"
                              radius="${cylinderJ2_radius}" 
                              length="${cylinderJ2_height}" />
    </inertial>
       
  </link>

  <link name="link2">

    <xacro:property name="link2_radius"   value="${ 45.0 * scale}"   />
    <xacro:property name="link2_length"   value="${ 274.0 * scale}"   />

    <xacro:property name="link2_mass"     value="0.43"   />
    
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${ 175.0 * scale }"/>
      <mass value="${link2_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${link2_mass}"
                              radius="${link2_radius}"
                              length="${link2_length}" />
    </inertial>

    <visual>
        <origin xyz="0.049 0 0" rpy="-${pi/2} 0 -${pi/2}" />
        <geometry>
          <mesh filename="$(find kr_robot_description)/kr810/meshes/a810/a810_Link3.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.2 0.2 0.2 1" />
        </material>
    </visual>


  </link>

  <link name="link3">

    <xacro:property name="link3_radius"        value="${  45.0 * scale}" />
    <xacro:property name="link3_length"        value="${ 142.9 * scale}" />
    <xacro:property name="link3_hinge_length"  value="${ 120.0 * scale}" />
    <xacro:property name="link3_hinge_radius"  value="${  45.0 * scale}" />
    <xacro:property name="link3_hinge_yoffset" value="${   6.5 * scale}" />

    <xacro:property name="link3_mass"     value="2.9" />

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="${link3_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${link3_mass}"
                              radius="${link3_radius}"
                              length="${link3_length}" />
    </inertial>
    
    <visual>
        <origin xyz="-0.05 -0.0 0.315" rpy="${pi/2} 0 -${pi/2}" />
        <geometry>
          <mesh filename="$(find kr_robot_description)/kr810/meshes/a810/a810_Link4.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.2 0.2 0.2 1" />
        </material>
    </visual>

  </link>

  <link name="linkJ4">

    <xacro:property name="cylinderJ4_radius"   value="${15.0 * scale}"   />
    <xacro:property name="cylinderJ4_height"   value="${100 * scale}"   />
    <xacro:property name="linkJ4_mass"         value="3.8"   />

    <xacro:visual_and_collision rpy="${pi/2} 0 0" 
                                xyz="0 ${13 * scale} 0"
                                material="orange">
      <cylinder length="${cylinderJ4_height * 1.29}" radius="${cylinderJ4_radius}"/>
    </xacro:visual_and_collision>
    
    <inertial>
      <origin rpy="0 0 0" xyz="0 ${6.5 * scale} 0"/>
      <mass value="${linkJ4_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${linkJ4_mass}"
                              radius="${cylinderJ4_radius}" 
                              length="${cylinderJ4_height}" />
    </inertial>
    
  </link>

  <link name="link4">

    <xacro:property name="link4_radius"   value="${  40.0 * scale}" />
    <xacro:property name="link4_length"   value="${ 271.0 * scale}" />

    <xacro:property name="link4_mass"     value="0.33" />

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${ 168.0 * scale}"/>
      <mass value="${link4_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${link4_mass}"
                              radius="${link4_radius}"
                              length="${link4_length}" />
    </inertial>
    
    <visual>
        <origin xyz="0.04 0.0005 0.0" rpy="-${pi/2} 0 ${pi/2}" />
        <geometry>
          <mesh filename="$(find kr_robot_description)/kr810/meshes/a810/a810_Link5.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.2 0.2 0.2 1" />
        </material>
    </visual>

  </link>

  <link name="link5">

    <xacro:property name="link5_radius"   value="${  40.0 * scale}" />
    <xacro:property name="link5_length"   value="${ 103.5 * scale}" />

    <xacro:property name="link5_mass"     value="1.7" />

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="${link5_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${link5_mass}"
                              radius="${link5_radius}"
                              length="${link5_length}" />
    </inertial>

    <visual>
        <origin xyz="0.0 0.002 0.1035" rpy="0 0 -${pi/2}" />
        <geometry>
          <mesh filename="$(find kr_robot_description)/kr810/meshes/a810/a810_Link6.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.2 0.2 0.2 1" />
        </material>
    </visual>


  </link>

  <link name="linkJ6">

    <xacro:property name="cylinderJ6_radius"   value="${ 15.0 * scale}"   />
    <xacro:property name="cylinderJ6_height"   value="${ 110.0 * scale}"  />
    <xacro:property name="linkJ6_mass"         value="1.8"   />
    <!--
    <xacro:visual_and_collision rpy="${pi/2} 0 0" 
                                xyz="0 ${10 * scale} 0"
                                material="orange">
      <cylinder length="${cylinderJ6_height * 1.9}" radius="${cylinderJ6_radius}"/>
    </xacro:visual_and_collision>
    -->
    <inertial>
      <origin rpy="0 0 0" xyz="0 ${4.0 * scale} 0"/>
      <mass value="${linkJ6_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${linkJ6_mass}"
                              radius="${cylinderJ6_radius}" 
                              length="${cylinderJ6_height}" />
    </inertial>
    
  </link>

  <link name="link6">
    <xacro:property name="link6_radius"   value="${ 35.0 * scale}" />
    <xacro:property name="link6_length"   value="${ 66.5 * scale}" />
    <xacro:property name="link6_mass"     value="1.8" />
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${4.0 * scale}"/>
      <mass value="${link6_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${link6_mass}"
                              radius="${link6_radius}"
                              length="${link6_length}" />
    </inertial>
    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <mesh filename="$(find kr_robot_description)/kr810/meshes/a810/a810_Link7.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.2 0.2 0.2 1" />
        </material>
    </visual>
  </link>

  <link name="end_effector">

    <xacro:property name="end_effector_outer_radius" value="${ 35.5 * scale}" />
    <xacro:property name="end_effector_outer_length" value="${ 5.0 * scale}" />
    <xacro:property name="end_effector_inner_radius" value="${ 22.5 * scale}" />
    <xacro:property name="end_effector_inner_length" value="${ 5.0   * scale}" />

    <xacro:property name="end_effector_mass"         value="0.56"   />
    <visual>
        <origin xyz="0.0 -0.0 0.0" rpy="0 0 0" />
        <geometry>
          <mesh filename="$(find kr_robot_description)/kr810/meshes/a810/a810_ToolIO.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.8 0.8 0.8 1" />
        </material>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${-19.7 * scale}"/>
      <mass value="${end_effector_mass*mass_multiplier}"/>
      <xacro:cylinder_inertia mass="${end_effector_mass}"
                              radius="${end_effector_outer_radius}"
                              length="${end_effector_outer_length + end_effector_inner_length}" />
    </inertial>
  </link>

  <!-- joints -->
  <!-- <joint name="dummy" type="fixed">
    <parent link="world"/>
    <child link="base"/>
  </joint> -->


  <joint name="joint_1" type="continuous">
    <parent link="base"/>
    <child link="link1"/>
    <origin rpy="0 0 0" xyz="0 0 ${base_inner_height + base_outer_height}"/>

    <axis xyz="0 0 1"/>

    <dynamics damping="${joints_damping}"/>
    <limit effort="204" velocity="${225/180*pi}" lower="${-2*pi}" upper="${2*pi}"/>
    <!-- <limit effort="204" velocity="${225/180*pi}" lower="${-122.6 * pi_per_deg}" upper="${127.6 * pi_per_deg}"/> -->

  </joint>

  <xacro:property name="joint1_xoffset"  value="${  50.0 * scale}" />
  <xacro:property name="joint1_yoffset"  value="${   0.0 * scale}" />
  <xacro:property name="joint1_zoffset"  value="${ 308.7 * scale - 35 * scale}" />

  <joint name="joint_2" type="continuous">
    <parent link="link1"/>
    <child link="linkJ2"/>
    <origin rpy="0 0 0" xyz="${joint1_xoffset} ${joint1_yoffset} ${joint1_zoffset}"/>
    <axis xyz="0 1 0"/>

    <dynamics damping="${joints_damping}"/>
    <limit effort="204" velocity="${225/180*pi}" lower="${-70.0 * pi_per_deg}" upper="${(180/180)*pi}"/>
    <!-- <limit effort="204" velocity="${225/180*pi}" lower="${-31.9 * pi_per_deg}" upper="${168.5 * pi_per_deg}"/> -->

  </joint>

  <xacro:property name="jointPL2_xoffset"  value="${  -50.0 * scale}" />
  <xacro:property name="jointPL2_yoffset"  value="${  -85.7 * scale}" />

  <joint name="jointPL2" type="fixed">
    <parent link="linkJ2"/>
    <child link="link2"/>
    <origin rpy="0 0 0" xyz="${jointPL2_xoffset} ${jointPL2_yoffset} 0"/>
  </joint>

  <joint name="joint_3" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin rpy="0 0 0" xyz="0 0 ${link2_length}"/>
    <axis xyz="0 0 1"/>

    <dynamics damping="${joints_damping}"/>
    <limit effort="85" velocity="${225/180*pi}" lower="${-2*pi}" upper="${2*pi}"/>
    <!--  <limit effort="85" velocity="${225/180*pi}" lower="${-177.6 * pi_per_deg}" upper="${177.6 * pi_per_deg}"/> -->

  </joint>

  <xacro:property name="joint3_xoffset"  value="${ 40.0 * scale}" />
  <xacro:property name="joint3_yoffset"  value="${ 0.0 * scale}" />
  <xacro:property name="joint3_zoffset"  value="${ 142.9 * scale}" />

  <joint name="joint_4" type="continuous">
    <parent link="link3"/>
    <child link="linkJ4"/>
    <origin rpy="0 0 0" xyz="${joint3_xoffset} ${joint3_yoffset} ${joint3_zoffset}"/>
    <axis xyz="0 1 0"/>

    <dynamics damping="${joints_damping}"/>
    <limit effort="85" velocity="${225/180*pi}" lower="${-70.0 * pi_per_deg}" upper="${(180/180)*pi}"/>
    <!-- <limit effort="85" velocity="${225/180*pi}" lower="${-20.6 * pi_per_deg}" upper="${152.1 * pi_per_deg}"/> -->

  </joint>

  <xacro:property name="jointPL4_xoffset"  value="${ -40.0 * scale}" />
  <xacro:property name="jointPL4_yoffset"  value="${ 84.05 * scale}" />
  <xacro:property name="jointPL4_zoffset"  value="${ 0.0 * scale}" />

  <joint name="jointPL4" type="fixed">
    <parent link="linkJ4"/>
    <child link="link4"/>
    <origin rpy="0 0 0" xyz="${jointPL4_xoffset} ${jointPL4_yoffset} ${jointPL4_zoffset}"/>
  </joint>
  
  <joint name="joint_5" type="continuous">
    <parent link="link4"/>
    <child link="link5"/>
    <origin rpy="0 0 0" xyz="0 0 ${link4_length}"/>
    <axis xyz="0 0 1"/>

    <dynamics damping="${joints_damping}"/>
    <limit effort="51" velocity="${225/180*pi}" lower="${-2*pi}" upper="${2*pi}"/>
    <!-- <limit effort="51" velocity="${225/180*pi}" lower="${-177.6 * pi_per_deg}" upper="${177.6 * pi_per_deg}"/> -->


  </joint>

  <xacro:property name="joint5_zoffset"  value="${ 103.5 * scale}" />

  <joint name="joint_6" type="continuous">
    <parent link="link5"/>
    <child link="linkJ6"/>
    <origin rpy="0 0 0" xyz="0 0 ${joint5_zoffset}"/>
    <axis xyz="0 1 0"/>

    <dynamics damping="${joints_damping}"/>
    <limit effort="51" velocity="${225/180*pi}" lower="${-2*pi}" upper="${2*pi}"/>
    <!--    <limit effort="51" velocity="${225/180*pi}" lower="${-177.6 * pi_per_deg}" upper="${177.6 * pi_per_deg}"/> -->

  </joint>

  <xacro:property name="jointPL6_yoffset"  value="${ 111.0 * scale}" />
  <joint name="jointPL6" type="fixed">
    <parent link="linkJ6"/>
    <child link="link6"/>
    <origin rpy="0 0 0" xyz="0 ${jointPL6_yoffset} 0"/>
  </joint>

  <xacro:property name="joint6_zoffset"  value="${ 108.0 * scale}" />

  <joint name="joint_7" type="continuous">
    <parent link="link6"/>
    <child link="end_effector"/>
    <origin rpy="0 0 0" xyz="0 0 ${joint6_zoffset}"/>
    <axis xyz="0 0 1"/>

    <dynamics damping="${joints_damping}"/>

    <limit effort="51" velocity="${225/180*pi}" lower="${-2*pi}" upper="${2*pi}"/>
    <!-- <limit effort="51" velocity="${225/180*pi}" lower="${-177.6 * pi_per_deg}" upper="${177.6 * pi_per_deg}"/> -->

  </joint>


  <!-- gazebo -->
  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>
  <joint name="joint_world" type="fixed">
    <parent link="world"/>
    <child link="base"/>
  </joint>

  <ros2_control name="GazeboSimSystem" type="system">
    <hardware>
      <!-- Gazebo Harmonic backend -->
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <!-- 7 revolute joints, position command -->
    <joint name="joint_1">
      <command_interface name="position">
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">1.0</param>
      </state_interface>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint_2">
      <command_interface name="position">
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">-1.0</param>
      </state_interface>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint_3">
      <command_interface name="position">
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">1.0</param>
      </state_interface>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint_4">
      <command_interface name="position">
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">1.0</param>
      </state_interface>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint_5">
      <command_interface name="position">
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">1.0</param>
      </state_interface>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint_6">
      <command_interface name="position">
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">1.0</param>
      </state_interface>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint_7">
      <command_interface name="position">
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">1.0</param>
      </state_interface>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  </xacro:macro>

  <xacro:kr810_description />

  <xacro:arg name="controllers_file" default="BLAH!"/>

  <gazebo>
    <plugin filename="libgz_ros2_control-system.so"
            name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <!-- Point to the controllers YAML we’ll create below -->
      <parameters>$(arg controllers_file)</parameters>

      <!-- Optional tuning (documented by gz_ros2_control): -->
      <!-- <position_proportional_gain>0.3</position_proportional_gain> -->
      <!-- <hold_joints>true</hold_joints> -->
    </plugin>
  </gazebo>

</robot>