controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


kr810_controller:
  ros__parameters:
    type: kr_robot_driver/RobotController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity
