# Tells controller_manager its update rate and which controllers exist (their types)
controller_manager:
  ros__parameters:
    update_rate: 400        # Hz; choose what you want CM to tick at
    # use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6, joint_7]
    command_interfaces: [position]         # what your hardware exposes for commands
    state_interfaces:   [position, velocity]  # what your hardware exposes as state
